CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ownerId INT NOT NULL,
    title VARCHAR(100),
    originalFilePath VARCHAR(255) NOT NULL,
    uploadedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lastEditedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ownerId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE ImageVersions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    imageId INT NOT NULL,
    filePath VARCHAR(255) NOT NULL,
    versionNumber INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (imageId) REFERENCES Images(id) ON DELETE CASCADE
);